name: allActions
on:
    push:
        branches: [ "main" ]
    workflow_dispatch:
jobs:
    call-test:
        uses: ./.github/workflows/test.yaml
    call-deploy:
        if: startsWith(github.ref, 'refs/tags/v')
        needs: call-test
        uses: ./.github/workflows/deploy.yaml