name: main
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  call-test:
    uses: ./.github/workflows/test.yaml
  call-deploy:
    needs: call-test
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/deploy.yaml